### ISSUE TITLE
"press any key to continue" crash Win32Exception failed to start process during debugging

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#103]
No repro steps, but we can potentially just catch this exception.
An exception of type 'System.ComponentModel.Win32Exception' occurred in Microsoft.NodejsTools.dll but was not handled in user code

>   at Microsoft.NodejsTools.Debugger.NodeProcess.Start() in c:\myntvs\Nodejs\Product\Nodejs\Debugger\NodeProcess.cs:line 91
>    at Microsoft.NodejsTools.Debugger.NodeDebugger.Start(Boolean startListening) in c:\myntvs\Nodejs\Product\Nodejs\Debugger\NodeDebugger.cs:line 157
>    at Microsoft.NodejsTools.Debugger.DebugEngine.AD7Engine.Microsoft.VisualStudio.Debugger.Interop.IDebugEngineLaunch2.LaunchSuspended(String pszServer, IDebugPort2 port, String exe, String args, String dir, String env, String options, enum_LAUNCH_FLAGS launchFlags, UInt32 hStdInput, UInt32 hStdOutput, UInt32 hStdError, IDebugEventCallback2 ad7Callback, IDebugProcess2& process) in c:\myntvs\Nodejs\Product\Nodejs\Debugger\DebugEngine\AD7Engine.cs:line 563

**Comment by mousetraps** [comment]
actually nevermind. this was caught somewhere down the line. the debugger tricked me. :smiley:

**Comment by mousetraps** [comment]
![image](https://cloud.githubusercontent.com/assets/762848/7509568/22c75602-f447-11e4-84f2-4a30976d71fb.png)

**Comment by mousetraps** [comment]
Okay I figured out when this issue occurs. It happens right after I switch Node.js versions using nvm, and that goes wrong for some reason (you'd also get the same message in the cmd prompt, sans the "press any key help stopped working" message. Typically another `nvm use` solves the issue.
