### ISSUE TITLE
Exception on Delete Typings Folder

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1191]
##### Expected Behavior

Delete typings folder
##### Actual Behavior

Exception thrown but folder is properly deleted.

```
System.InvalidOperationException: Node not found
   at Microsoft.VisualStudioTools.Project.HierarchyNode.RemoveChild(HierarchyNode node) in C:\source\nodejstools\Common\Product\SharedProject\HierarchyNode.cs:line 565
   at Microsoft.NodejsTools.Project.NodejsFolderNode.RemoveChild(HierarchyNode node) in C:\source\nodejstools\Nodejs\Product\Nodejs\Project\NodejsFolderNode.cs:line 116
   at Microsoft.VisualStudioTools.Project.CommonProjectNode.FileSystemChange.ChildDeleted(HierarchyNode child) in C:\source\nodejstools\Common\Product\SharedProject\CommonProjectNode.cs:line 1130
   at Microsoft.VisualStudioTools.Project.CommonProjectNode.FileSystemChange.ProcessChange() in C:\source\nodejstools\Common\Product\SharedProject\CommonProjectNode.cs:line 1075
   at Microsoft.VisualStudioTools.Project.CommonProjectNode.OnIdle(Object sender, ComponentManagerEventArgs e) in C:\source\nodejstools\Common\Product\SharedProject\CommonProjectNode.cs:line 1025
   at Microsoft.VisualStudioTools.Project.CommonProjectNode.OnIdle(Object sender, ComponentManagerEventArgs e) in C:\source\nodejstools\Common\Product\SharedProject\CommonProjectNode.cs:line 1029
   at Microsoft.VisualStudioTools.IdleManager.FDoIdle(UInt32 grfidlef) in C:\source\nodejstools\Common\Product\SharedProject\IdleManager.cs:line 70

Exception thrown: 'System.InvalidOperationException' in Microsoft.NodejsTools.dll
```
##### Steps to Reproduce
1. Create new js console app with NTVS 1.2 and ES6 IntelliSense
2. Allow typings to be downloaded.
3. Delete a sub folder in typings (such as `typings/globals/node` or `typings/globals` or just `typings`)

**Comment by mjbvz** [comment]
I also recently hit then when deleting a `node_modules` folder that was not even included in the project.

**Comment by uniqueiniquity** [comment]
I was unable to reproduce this exception in VS 2017.
Are you still able to consistently reproduce this?
