### ISSUE TITLE
Can't view myget npm packages in "Install new npm Packages" window

### ISSUE THREAD

**Issue by rmcduffie** [Microsoft/nodejstools#1217]
##### Expected Behavior 
To be able to view npm packages from our remote myget package feed after invoking the "Install new npm Packages" window from the VS2015 solution explorer
##### Actual Behavior 
After invoking the "Install new npm Packages" window it shows the "Refresh failed" error and displays the following error in the output window.
I've tried clearing my npm cache multiple times but the error persists.
Note: in the below error message I substituted [APIKEY] for my actual myget API Key value.
````
********************************************************************************************************
Registry url: https://www.myget.org/F/lexisnexis/auth/[APIKEY]/npm/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\mcduffrx\AppData\Local\Microsoft\Node.js Tools\NpmCache\d696b64a-1438-4b01-9230-31a0475bafb2\all_packages.json
Downloading list of packages from https://www.myget.org/F/lexisnexis/auth/[APIKEY]/npm/-/all
Download complete - updating database
Reading 611 bytes from C:\Users\mcduffrx\AppData\Local\Microsoft\Node.js Tools\NpmCache\d696b64a-1438-4b01-9230-31a0475bafb2\all_packages.json (8/23/2016 3:35:09 PM)
Microsoft.NodejsTools.Npm.SemverVersionFormatException: Invalid semantic version: 'latest'. The version number must consist of three non-negative numeric parts of the form MAJOR.MINOR.PATCH, with optional pre-release and/or build metadata. The optional parts may only contain characters in the set [0-9A-Za-z-].
   at Microsoft.NodejsTools.Npm.SemverVersion.Parse(String versionString)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<GetVersions>d__11.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.NodejsTools.Npm.NodeModuleBuilder.set_AvailableVersions(IEnumerable`1 value)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackage(JsonTextReader jsonReader, NodeModuleBuilder builder)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
Download or parsing failed - deleting C:\Users\mcduffrx\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting d696b64a-1438-4b01-9230-31a0475bafb2
Microsoft.NodejsTools.Npm.SemverVersionFormatException: Invalid semantic version: 'latest'. The version number must consist of three non-negative numeric parts of the form MAJOR.MINOR.PATCH, with optional pre-release and/or build metadata. The optional parts may only contain characters in the set [0-9A-Za-z-].
   at Microsoft.NodejsTools.Npm.SemverVersion.Parse(String versionString)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<GetVersions>d__11.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.NodejsTools.Npm.NodeModuleBuilder.set_AvailableVersions(IEnumerable`1 value)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackage(JsonTextReader jsonReader, NodeModuleBuilder builder)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.NmpCommandRunner.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__12.MoveNext()
********************************************************************************************************
Here is the content of the all_packages.json file contained in the NpmCache folder:
{"_updated":1471969562381,"test_node_app":{"name":"test_node_app","version":"1.0.0","description":"NodejsConsoleApp1","main":"app.js","author":{"name":"MCDUFFRX"},"dist-tags":{"latest":"1.0.0"},"time":{"modified":"2016-08-22T18:09:52.52Z"},"versions":{"latest":"1.0.0"}},"testnodejs":{"name":"testnodejs","version":"1.2.11","description":"test npm module","main":"index.js","scripts":{"test":"echo \"Error: no test specified\" && exit 1"},"author":"Rob McDuffie <rmcduffie@nc.rr.com>","license":"ISC","dist-tags":{"latest":"1.2.11"},"time":{"modified":"2016-08-19T14:47:23.23Z"},"versions":{"latest":"1.2.11"}}}
```
*********************************************************************************************************
<!---(from Help -> About Microsoft Visual Studio)-->
- NTVS Version: 1.2.40726.00
- Visual Studio Version:  14.0.25425.01 Update 3
- Node.js Version: 3.10.7

##### Steps to Reproduce
1. Upload a package(s) to the myget npm package feed
2. Configure the local node npm registry to point to the myget npm package feed using the pre-authenticated URL with the API key.
3. right click on the "npm" icon in solution explorer and select the "Install new npm Packages" menu item.

**Comment by mjbvz** [comment]
Looks like the root cause is that we are trying to parse `"latest"` as a semver string, and failing. We actually handle this sort of error other locations, but not in this calling path.

Two possible fixes:

* Catch and ignore the exception or print out something when parsing fails.
* Fix the versions parsing logic to handle these cases properly
