### ISSUE TITLE
Newtonsoft.Json.JsonException Unexpcted JSON token at start of NPM catalog data

### ISSUE THREAD

**Issue by Stevio54** [Microsoft/nodejstools#1317]
My issue is that if I load https://registry.npmjs.org/-/all directly into my browser I get nothing. 

Other URL's work such as https://registry.npmjs.org/-/all/static/all.json

So, as seen in the output below, it fails to update my catalog on first opening. 

I am on VS 2015, using the latest build from 10/5/2016 for Node JS Tools. 

Here is the output of the Install Output:

Registry url: https://registry.npmjs.org/
Your package catalog database needs to be upgraded. Please wait while we execute a full refresh.
Deleting C:\Users\s2cc\AppData\Local\Microsoft\Node.js Tools\NpmCache
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\s2cc\AppData\Local\Microsoft\Node.js Tools\NpmCache\all_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all
Download complete - updating database
Reading 0 bytes from C:\Users\s2cc\AppData\Local\Microsoft\Node.js Tools\NpmCache\all_packages.json (10/6/2016 10:40:00 AM)
Newtonsoft.Json.JsonException: Unexpected JSON token at start of NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
Download or parsing failed - deleting C:\Users\s2cc\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting 16d830f2-3508-4aa5-9f4b-1c2362a73887
Newtonsoft.Json.JsonException: Unexpected JSON token at start of NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.NmpCommandRunner.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__12.MoveNext()

**Comment by Stevio54** [comment]
So, I think I fixed it myself. 

I used the commands below:

SET http_proxy=[MY PROXY]
SET https_proxy=[MY PROXY]

After doing this and deleting the NpmCache folder, the issue seems to have resolved itself.

**Comment by vladimir77** [comment]
There is more simple way: you need to add all required packages to 'package.json'.

**Comment by bala41288** [comment]
Can you please explain how you fixed this?

I'm having exactly the same error now. I have tried all the possibilities but couldn't fix it. 

Can you please help?

**Comment by moinuddin14** [comment]
@bala41288 If you are using Visual Studio then you can create a package.json file [like this](https://gist.github.com/moinuddin14/46528d3fc036abbf1a4eb98a546d8996)

On Saving it should by default download the required packages that you have placed under dependencies object. If you find any issues, then go to the npm>"dependencyName" & npm>dev>"dependencies" and right click on them and click on "Install missing npm Package(s)". You can see in the below screenshot that i have "gulp" in red which means its successfully installed and "gulp-protractor" in yellow that means it's not installed. 

![image](https://cloud.githubusercontent.com/assets/1734908/26818410/2ec3c390-4ab8-11e7-94ec-3f4d2a6e08af.png)

Now, right click on the missing package (i.e., in the yellow) and select "Install missing npm Package(s)". You should now see that npm module is also installed and turned into red as shown in the below image 

![image](https://cloud.githubusercontent.com/assets/1734908/26818546/b0f5e226-4ab8-11e7-916e-1b9ee2c422f5.png)
