### ISSUE TITLE
Debugging from a webpage

### ISSUE THREAD

**Issue by jrmora** [Microsoft/nodejstools#14]
Hi,
I have a Node.js project that is intended to be used for a website HTML5 + canvas.
Inside his node_modules there is a nested reference to "domify" (turn HTML into DOM elements)

While debugging require(), the next error is displayed, beacuse (of course) no "document" element exists, I am starting from a javascript: 

Debugger listening on port 5858
D:\xxx\node_modules\min-dom\node_modules\domify\index.js:12
var div = document.createElement('div');
               ^
ReferenceError: document is not defined
    at Object.<anonymous> (D:\xxx\node_modules\min-dom\node_modules\do
mify\index.js:12:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\xxx\node_modules\min-dom\lib\domify.js:1
:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Press any key to continue...

The question is, how can I start the debugger from a webpage in order to have a "document" and pass this error?

Thank you

**Comment by MystK** [comment]
I'm not sure if this belongs here as you are having trouble with your code instead of actually the debugger or NVST. 

It sounds so me that you'd get that error regardless of if you ran it with the debugger or outside of Visual Studio.

**Comment by mousetraps** [comment]
Yeah, it's not clear to me what you expect the experience to be. Are you trying to start with and debug client-side code without actually using Node? If so, see comments on this issue for more details
https://nodejstools.codeplex.com/workitem/1418
