### ISSUE TITLE
NPM registry refresh is not working

### ISSUE THREAD

**Issue by spoofi** [Microsoft/nodejstools#1592]
https://registry.npmjs.org/-/all returns a blank page.

##### Actual Behavior 
NPM registry refresh is not working

- NTVS Version: 1.3.50417.1
- Visual Studio Version:  Community 2017 (Version 15.2 (26430.6) Release)
- Node.js Version: v6.10.3

##### Steps to Reproduce
1. Create new empty node.js app
2. Trying to install new npm package
3. Error, see below
```
Registry url: https://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\username\AppData\Local\Microsoft\Node.js Tools\NpmCache\e6da80a6-25d9-40fd-a85e-7a16926dfce2\all_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all
Download complete - updating database
Reading 0 bytes from C:\Users\username\AppData\Local\Microsoft\Node.js Tools\NpmCache\e6da80a6-25d9-40fd-a85e-7a16926dfce2\all_packages.json (30-May-17 4:04:19 PM)
Newtonsoft.Json.JsonException: Unexpected JSON token at start of NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
Download or parsing failed - deleting C:\Users\username\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting e6da80a6-25d9-40fd-a85e-7a16926dfce2
Newtonsoft.Json.JsonException: Unexpected JSON token at start of NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.NmpCommandRunner.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__12.MoveNext()
```

**Comment by kant2002** [comment]
@spoofi  This is likely related to NPM 5.0 being released today. Not directly related to NTVS. Also likely this is related to https://github.com/npm/registry/issues/159

**Comment by spoofi** [comment]
@kant2002 Thanks for comment, for now it works. Indeed, the problem was linked to the NPM registry, and no code changes required.
