### ISSUE TITLE
cannot install NPM package

### ISSUE THREAD

**Issue by leliselenium** [Microsoft/nodejstools#1617]
I tried to install NPM package on VS 2012 and I am getting the following error:
we used  NTVS1.1.1 VS-2012 version.

Registry url: https://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\lglickx\AppData\Local\Microsoft\Node.js Tools\NpmCache\c6e56cc7-965c-41bb-8c35-ec018a3f3f7c\all_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all
Download complete - updating database
Reading 24 bytes from C:\Users\lglickx\AppData\Local\Microsoft\Node.js Tools\NpmCache\c6e56cc7-965c-41bb-8c35-ec018a3f3f7c\all_packages.json (7/12/2017 1:15:55 PM)
Newtonsoft.Json.JsonException: Unexpected JSON token reading a package from the NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass7_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass25_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__25.MoveNext()
Download or parsing failed - deleting C:\Users\lglickx\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting c6e56cc7-965c-41bb-8c35-ec018a3f3f7c
Newtonsoft.Json.JsonException: Unexpected JSON token reading a package from the NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass7_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass25_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__13.MoveNext()

**Comment by paulvanbrenk** [comment]
It looks like NPM shut down the registry we use to populate the NPM catalog early, as this wasn't supposed to happen till September [0].

The good news is, this should work in NTVS 1.3 for VS 2015, and VS2017 Update 3. The bad news is we no longer support NTVS on VS 2012.


[0] http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint
