### ISSUE TITLE
Unable to refresh packages

### ISSUE THREAD

**Issue by RevealedFrom** [Microsoft/nodejstools#1639]
##### Expected Behavior 
The Install New npm Packages dialog says "Installed locally More than 1 month ago." So I clicked Refresh. In the past, the packages could be updated, 

##### Actual Behavior 
But for the past month or so, it always end up with **Installed locally Refreshed failed - see output**

Output shows:

Registry url: https://registry.npmjs.org/
Current Time: 7/25/2017 13:45:34
Last Refreshed: 6/9/2017 21:25:14
Number of Results: 469043
Registry url: https://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\xxx\AppData\Local\Microsoft\Node.js Tools\NpmCache\2de06639-f26a-4d91-bd20-9a56589ad75d\since_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1497012891981
Download complete - updating database
Reading 24 bytes from C:\Users\xxx\AppData\Local\Microsoft\Node.js Tools\NpmCache\2de06639-f26a-4d91-bd20-9a56589ad75d\since_packages.json (7/25/2017 13:47:02)
Newtonsoft.Json.JsonException: Unexpected JSON token reading a package from the NPM catalog data
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ReadPackagesFromObject(SQLiteConnection db, JsonTextReader jsonReader, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass6_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass23_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

- NTVS Version: 1.3.50201.08
- Visual Studio Version: 2017
- Node.js Version: 6.9.2

##### Steps to Reproduce
1.  As described in Expected behavior
2.

**Comment by paulvanbrenk** [comment]
That wasn't supposed to happen till 9/1, fortunately we fixed this in VS 2017 Update 3, preview 5 was released earlier this week.
http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint
