### ISSUE TITLE
How can I use babel to transpile my ES6 code before debugging node

### ISSUE THREAD

**Issue by JoshLefebvre** [Microsoft/nodejstools#1697]
I'm wondering if there is somewhere in the node debugger that I can supply an argument with babel to transpile my es6 nodejs code (specifically the import keyword)  to es5? Whenever I try to debug my express application I get the following: 

> (function (exports, require, module, __filename, __dirname) { import express from 'express'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:386:11)

- NTVS Version:  1.41
- Visual Studio Version:  Visual Studio 2017 v15.3
- Node.js Version:  6.11.3

**Comment by paulvanbrenk** [comment]
Currently we don't support pre/post build steps for JavaScript projects, the easiest way to make this work is to switch to TypeScript.
