### ISSUE TITLE
Running test with vstest.console.exe using the test adapter fails.

### ISSUE THREAD

**Issue by ashwini-ms** [Microsoft/nodejstools#1929]
##### Expected Behavior 
Unable to node js test using test adapter through vstets.console.exe from cmd. I am using following command 

 C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Node.js Tools for Visual Studio\1.3>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "<path_to_test_project>\NodejsConsoleApp1\UnitTest1.js"  /TestAdapterPath:.  /UseVsixExtensions:true /listtests /platform:x64

Not getting tests list.

I looked at the vstest.console.exe trace and I see following exception:

1) Could not load file or assembly 'Microsoft.VisualStudio.Settings.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Resulting in: An exception occurred while trying to create an instance of type 'Microsoft.PythonTools.Interpreter.InterpreterOptionsService'.

Resulting in: Cannot activate part 'Microsoft.PythonTools.Interpreter.InterpreterOptionsService'.
Element: Microsoft.PythonTools.Interpreter.InterpreterOptionsService -->  Microsoft.PythonTools.Interpreter.InterpreterOptionsService -->  AssemblyCatalog (Assembly="Microsoft.PythonTools.VSInterpreters, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")

Resulting in: Cannot get export 'Microsoft.PythonTools.Interpreter.InterpreterOptionsService (ContractName="Microsoft.PythonTools.Interpreter.IInterpreterOptionsService")' from part 'Microsoft.PythonTools.Interpreter.InterpreterOptionsService'.
Element: Microsoft.PythonTools.Interpreter.InterpreterOptionsService (ContractName="Microsoft.PythonTools.Interpreter.IInterpreterOptionsService") -->  Microsoft.PythonTools.Interpreter.InterpreterOptionsService -->  AssemblyCatalog (Assembly="Microsoft.PythonTools.VSInterpreters, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[T](String contractName, ImportCardinality cardinality)
   at Microsoft.PythonTools.InterpreterOptionsServiceProvider.GetService(VisualStudioApp app)
   at Microsoft.PythonTools.TestAdapter.TestDiscoverer..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.VisualStudio.TestPlatform.Common.RockSteady.TestPluginsFramework.TestPluginManager.CreateTestExtension[T](Type extensionType)
E, 27380, 13, 2018/04/16, 11:08:23.172, 810334653320, vstest.discoveryengine.exe, TestDiscoveryManager: LoadExtensions: Exception occured while loading extensions System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

##### Actual Behavior 
No test case is listed.

- NTVS Version: 1.3
- Visual Studio Version:  2015
- Node.js Version: 8.10

##### Steps to Reproduce
1.  Run node js test from command line using vstest.console.exe

**Comment by ashwini-ms** [comment]
I was able to run this when using .njsproj file. Is there a way to provide the test file directly ?  Since we want to use the adapter in a CI build, having the proj file in the build drop doesn't look like a good pattern here.  Can the test adapter accepts the folder for test discovery and execution.

**Comment by paulvanbrenk** [comment]
No, for VS 2015 we only support the project file. We are planning some changes, but nothing concrete yet.

Can you run the testframework direct, i.e. not use the test adapter. e.g. `jasmine <path to js file>`
