### ISSUE TITLE
Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

### ISSUE THREAD

**Issue by GeoffreyEmery** [Microsoft/nodejstools#208]
vs version  = 2015rc
windows version = 8.1
steps to reproduce 
new -> project -> basic azure node.js express 4 application
every time i run it i get t the same error. It still works but its super annoying to have see this every time. I tried the same in the VS 2013 and the same error occurs i installed the nuget package 
http://www.nuget.org/packages/Newtonsoft.Json
Still same thing. 

```
------------------------------------
--- error 
------------------------------------
Error - Cannot load global packages.
System.AggregateException: One or more errors occurred. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\Users\Geoffrey\AppData\Roaming\npm\node_modules\azure\node_modules\azure-storage\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JTokenWriter.AddValue(JValue value, JsonToken token)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteNull()
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEndObject()
   at Newtonsoft.Json.JsonWriter.WriteEnd(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEnd()
   at Newtonsoft.Json.JsonWriter.AutoCompleteAll()
   at Newtonsoft.Json.Linq.JTokenWriter.Close()
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource.WrapExceptionAndRethrow(String fullPathToFile, Exception ex)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   at Microsoft.NodejsTools.Npm.DirectoryPackageJsonSource..ctor(String fullDirectoryPath)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\Users\Geoffrey\AppData\Roaming\npm\node_modules\azure\node_modules\azure-storage\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JTokenWriter.AddValue(JValue value, JsonToken token)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteNull()
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEndObject()
   at Newtonsoft.Json.JsonWriter.WriteEnd(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEnd()
   at Newtonsoft.Json.JsonWriter.AutoCompleteAll()
   at Newtonsoft.Json.Linq.JTokenWriter.Close()
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource.WrapExceptionAndRethrow(String fullPathToFile, Exception ex)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   at Microsoft.NodejsTools.Npm.DirectoryPackageJsonSource..ctor(String fullDirectoryPath)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()<---
Error - Cannot load global packages.
System.AggregateException: One or more errors occurred. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\Users\Geoffrey\AppData\Roaming\npm\node_modules\azure\node_modules\azure-storage\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JTokenWriter.AddValue(JValue value, JsonToken token)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteNull()
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEndObject()
   at Newtonsoft.Json.JsonWriter.WriteEnd(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEnd()
   at Newtonsoft.Json.JsonWriter.AutoCompleteAll()
   at Newtonsoft.Json.Linq.JTokenWriter.Close()
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource.WrapExceptionAndRethrow(String fullPathToFile, Exception ex)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   at Microsoft.NodejsTools.Npm.DirectoryPackageJsonSource..ctor(String fullDirectoryPath)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\Users\Geoffrey\AppData\Roaming\npm\node_modules\azure\node_modules\azure-storage\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JTokenWriter.AddValue(JValue value, JsonToken token)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteNull()
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEndObject()
   at Newtonsoft.Json.JsonWriter.WriteEnd(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEnd()
   at Newtonsoft.Json.JsonWriter.AutoCompleteAll()
   at Newtonsoft.Json.Linq.JTokenWriter.Close()
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   --- End of inner exception stack trace ---
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource.WrapExceptionAndRethrow(String fullPathToFile, Exception ex)
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile)
   at Microsoft.NodejsTools.Npm.DirectoryPackageJsonSource..ctor(String fullDirectoryPath)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__32.MoveNext()<---

```

**Comment by mousetraps** [comment]
Thx for reporting. This is occurring due to the azure-storage package.json file from the azure package that you've installed globally. Unfortunately I can't reproduce it, so maybe things have changed in the latest version. Does updating/re-installing the azure package help?

**Comment by mousetraps** [comment]
any luck on this?

**Comment by GeoffreyEmery** [comment]
hey @mousetraps,
   So I uninstalled azure-storage and re-installed it.. no dice.. 
   I uninstalled all the global modules no dice again.. very not cool ... add picture so  you can see i was convinced...looked at the error seems to be going to my roaming directory.. thats i thought what is there.. looked there and it seems to be installing all my modules in that location..  found this... 
Scroll down to the problem with installing in this location
https://github.com/npm/npm/wiki/Troubleshooting
and i remembered way back in the day when i first started using a windows box for doing node work and i encountered this same odity.. you install node in one place and windows puts in modules in some other place... maybe you guys should help them out with a better solution to that. You code worked fine it booted up the bootstrap express app. thanks for checking in and I hope you can maybe help node community simplify the windows install locations.

**Comment by GeoffreyEmery** [comment]
![2015-07-14_22-25-58](https://cloud.githubusercontent.com/assets/3301804/8691685/df9fb92c-2a7a-11e5-9dba-7b4389ba2787.png)
![2015-07-14_22-25-58](https://cloud.githubusercontent.com/assets/3301804/8691703/1eb333e6-2a7b-11e5-8fd2-6c6b6f5fc623.png)

**Comment by GeoffreyEmery** [comment]
so small update from this morning i went ahead and formatted the surface 3 and put windows 10 preview on it with VS 2015 RC and this has gone away.
I would say a tangential project for this team would be to help the node core team improve the windows development expierence overall. I believe this would help get even greater adoption for this great tool set and awesome ide your working on. thanks again for reaching out.

**Comment by mousetraps** [comment]
Glad you got it working, but let us know if you run into it again. We'll want the package version # to help us get the the bottom of it. 

We've been chatting with npm lately and we have a msft contributor on node core. We will bring this issue with the relevant folks and see how we can help.

**Comment by yannduran** [comment]
I'm also having this same problem. I'm using VS 2015 RTM & Windows 10 Build 10240.

I saw somewhere that "npm cache clean" helped some people with this, and while it reduced the total number of errors, they haven't all gone away.

See here for the full output (both before and after "npm cache clean") from the Npm output window when I issue an "npm update" command, by right-clicking the npm node in Solution Explorer:

http://pastebin.com/B7XgPWcU

I've also issued "npm update" from a command prompt. No errors are listed in the command prompt window itself, but performing an update from VS again still shows errors in the Npm output window.

I also notice that since I started using Windows 10, that the Npm packages that I've installed globally on the machine don't show up in the npm node of the project in solution explorer anymore like they used to. The global node is empty. The normal dependencies show up fine, as do any dev dependencies. Just thought I'd mention it in case there's a connection.

On another note, though still regarding NodeJS Tools for VS, it seems like Node.js code analysis isn't performed on a background thread, nor when the saved analysis file is being loaded by VS. On a number of occasions I've had VS be completely unresponsive until these tasks have completed. It's very annoying.

**Comment by bromi0** [comment]
I had this error when i've had npm installed with node .msi installator and had npm install -g npm so it put more recent version in my \appdata. But vstools updater was choking on some inner dependency of that 'recent' npm. After i've uninstalled it, update was working fine.

**Comment by sparkleholic** [comment]
I have a extract same issue..

**Comment by kant2002** [comment]
@sparkleholic or @GeoffreyEmery could you report version of installed global module which cause this exception?

**Comment by arangas** [comment]
This issue has started for me as well but working in a Cordova project with npm references. My npm and node versions are the same as @yannduran although i'm running Windows 8.1. The error I have is almost the same but the path is to Cordova's version of graceful-js.

When opening the solution, the following is logged to the output window:

```
====Executing command 'npm install'====



====npm command completed with exit code 0====


Error - Cannot load global packages.
System.AggregateException: One or more errors occurred. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'c:\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

[snipped for brevity]
```

**Comment by laurentiustamate94** [comment]
The problem (at least on my machine) was the `npm` folder in `aurelia-cli`. After installing aurelia-cli project locally I manually deleted `[project_root]\node_modules\aurelia-cli\node_modules\npm` folder and all the errors disappeared. I think the default/global npm binary that visual studio uses when automatically calling `npm install` interferes somehow with the globally installed one

**Comment by dazinator** [comment]
I have this same issue, and I also have Aurelia-cli installed. I am going to try @laurentiustamate94 suggestion.

**Comment by dazinator** [comment]
@laurentiustamate94 - you are a genius - that's fixed all these errors for me too! I still don't understand what the problem is because I am new to NPM. Is this down to an issue with Aurelia-Cli including an NPM folder? None of the other modules appear to include npm locally.. makes me suspicious!

**Comment by laurentiustamate94** [comment]
@dazinator I investigate [aurelia-cli](https://github.com/aurelia/cli/search?utf8=%E2%9C%93&q=npm) and found that this plugin only uses npm as a module to update the aurelia environment itself (which is a bit awkward because you can just run `npm install` not a wrapper in `aurelia update`)

**Comment by dazinator** [comment]
@laurentiustamate94 - ahhh I see! Yes it does seem odd to include npm from an npm dependency in such a way doesn't it. I'm guessing aurelia team have done this so they can easily / reliably locate npm exe (from local folder path) rather than searching for it at runtime when its needed during `aurelia update`. Feels a bit wrong to me but still also feels like it shouldn't completely break VS's (global) npm :) Thanks for digging deeper with this, will keep my eye on that issue you referenced!

**Comment by cicorias** [comment]
I'm seeing this as well, and seems related to a dependancy from ember-cli:  
```
====Executing command 'npm install'====


npm WARN package.json NodejsConsoleApp1@0.0.0 No repository field.

====npm command completed with exit code 0====


Registry url: https://registry.npmjs.org/
Current Time: 9/17/2015 9:04:32 PM
Last Refreshed: 7/20/2015 2:32:35 PM
Number of Results: 176846
====Executing command 'npm install async --save '====

npm WARN package.json NodejsConsoleApp1@0.0.0 No repository field.
npm WARN package.json NodejsConsoleApp1@0.0.0 No license field.
async@1.4.2 node_modules\async

====npm command completed with exit code 0====

Error - Cannot load global packages.
Error - Cannot load global packages.
System.AggregateException: One or more errors occurred. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\Users\Shawn\AppData\Roaming\npm\node_modules\ember-cli\node_modules\npm\node_modules\graceful-fs\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

The following error occurred:

Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Obj

```

## contents of the package.json

```
{
  "_args": [
    [
      "graceful-fs@latest",
      "/Users/isaacs/dev/npm/npm"
    ]
  ],
  "_from": "graceful-fs@latest",
  "_id": "graceful-fs@4.1.2",
  "_inCache": true,
  "_location": "/graceful-fs",
  "_nodeVersion": "2.2.1",
  "_npmUser": {
    "email": "isaacs@npmjs.com",
    "name": "isaacs"
  },
  "_npmVersion": "3.0.0",
  "_phantomChildren": {},
  "_requested": {
    "name": "graceful-fs",
    "raw": "graceful-fs@latest",
    "rawSpec": "latest",
    "scope": null,
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "/"
  ],
  "_shasum": "fe2239b7574972e67e41f808823f9bfa4a991e37",
  "_shrinkwrap": null,
  "_spec": "graceful-fs@latest",
  "_where": "/Users/isaacs/dev/npm/npm",
  "bugs": {
    "url": "https://github.com/isaacs/node-graceful-fs/issues"
  },
  "dependencies": {},
  "description": "A drop-in replacement for fs, making various improvements.",
  "version": "3.0.8",
  "repository": {
    "type": "git",
    "url": "git://github.com/isaacs/node-graceful-fs.git"
  },
  "main": "graceful-fs.js",
  "engines": {
    "node": ">=0.4.0"
  },
  "directories": {
    "test": "test"
  },
  "dist": {
    "shasum": "fe2239b7574972e67e41f808823f9bfa4a991e37",
    "tarball": "http://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.2.tgz"
  },
  "engines": {
    "node": ">=0.4.0"
  },
  "files": [
    "fs.js",
    "graceful-fs.js",
    "legacy-streams.js",
    "polyfills.js"
  ],
  "gitHead": "c286080071b6be9aa9ba108b0bb9b44ff122926d",
  "homepage": "https://github.com/isaacs/node-graceful-fs#readme",
  "keywords": [
    "fs",
    "module",
    "reading",
    "retry",
    "retries",
    "queue",
    "error",
    "errors",
    "handling",
    "EMFILE",
    "EAGAIN",
    "EINVAL",
    "EPERM",
    "EACCESS"
  ],
  "license": "ISC",
  "devDependencies": {
    "mkdirp": "^0.5.0",
    "rimraf": "^2.2.8",
    "tap": "^1.2.0"
  },
  "gitHead": "45c57aa5e323c35a985a525de6f0c9a6ef59e1f8",
  "bugs": {
    "url": "https://github.com/isaacs/node-graceful-fs/issues"
  },
  "homepage": "https://github.com/isaacs/node-graceful-fs#readme",
  "_id": "graceful-fs@3.0.8",
  "_shasum": "ce813e725fa82f7e6147d51c9a5ca68270551c22",
  "_from": "graceful-fs@>=3.0.8 <3.1.0",
  "_npmVersion": "2.10.1",
  "_nodeVersion": "2.0.1",
  "_npmUser": {
    "name": "isaacs",
    "email": "isaacs@npmjs.com"
  },
  "dist": {
    "shasum": "ce813e725fa82f7e6147d51c9a5ca68270551c22",
    "tarball": "http://registry.npmjs.org/graceful-fs/-/graceful-fs-3.0.8.tgz"
  },
  "maintainers": [
    {
      "name": "isaacs",
      "email": "i@izs.me"
    }
  ],
  "name": "graceful-fs",
  "optionalDependencies": {},
  "repository": {
    "type": "git",
    "url": "git+https://github.com/isaacs/node-graceful-fs.git"
  },
  "scripts": {
    "test": "node test.js | tap -"
  },
  "version": "4.1.2"
}
```

**Comment by cicorias** [comment]
Also, i've re-installed ember-cli to see if the latest will fix but no.

However, I see @arangas had same issue with same node_module dependency `  "name": "graceful-fs"`

**Comment by mousetraps** [comment]
FYI This is an issue on the NTVS side - I have a PR out with the fix, which I can hopefully iterate on and merge in soon. 
https://github.com/Microsoft/nodejstools/issues/459

Well post again here wen we have a build out with the fix.

**Comment by arangas** [comment]
Woohoo thanks!

**Comment by mousetraps** [comment]
The fix is now available in our [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by laurentiustamate94** [comment]
:+1: :+1: :+1:

**Comment by fargs** [comment]
FYI for anyone still running into this issue. 

aurelia-cli is deprecated. See [here](https://github.com/aurelia/cli). 
The aurelia navigation skeleton app seems to be using the following packages in its place.

aurelia-bundler
aurelia-tools
