### ISSUE TITLE
Incorrect binary search result handling crashes VS

### ISSUE THREAD

**Issue by sharwell** [Microsoft/nodejstools#2138]
~~The correct expression here would be `~startIndex`.~~

This expression fails to handle the case where `BinarySearch` returns -1.

https://github.com/Microsoft/nodejstools/blob/05c00278246d81e978bf4a5236c2fa4c80e9dc96/Nodejs/Product/Nodejs/Repl/ReplOutputClassifier.cs#L50

This showed up in the following crash:

```
Event Time (UTC): 2/27/2019 9:34:50 PM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.NodejsTools.Repl.ReplOutputClassifier.GetClassificationSpans(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__46.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.TestExtensionErrorHandler.HandleError(System.Object, System.Exception)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.HandleException(System.Object, System.Exception)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1+<GetTagsForBuffer>d__46[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1+<GetTagsForBuffers>d__49[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregator.InternalGetClassificationSpans(Microsoft.VisualStudio.Text.SnapshotSpan, System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Text.Tagging.IMappingTagSpan`1<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>>)
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregator.GetClassificationSpans(Microsoft.VisualStudio.Text.SnapshotSpan)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.NormalizedSpanGenerator.CreateClassifiedRuns(Microsoft.VisualStudio.Text.SnapshotSpan, Microsoft.VisualStudio.Text.Classification.IAccurateClassifier, Microsoft.VisualStudio.Text.Classification.IClassificationFormatMap, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.NormalizedSpanGenerator.Create(Microsoft.VisualStudio.Text.Formatting.ITextAndAdornmentCollection, Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.Classification.IAccurateClassifier, Microsoft.VisualStudio.Text.Classification.IClassificationFormatMap, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLineSource.FormatLineInVisualBuffer(Microsoft.VisualStudio.Text.ITextSnapshotLine, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.FormatSnapshotLine(Microsoft.VisualStudio.Text.ITextSnapshotLine, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView+LayoutLineCache.FormatLineAndSetTransforms(LayoutDescription, Microsoft.VisualStudio.Text.ITextSnapshotLine, Boolean, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.LayoutRemainingLines(LayoutDescription, System.Nullable`1<System.Threading.CancellationToken>, Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.SnapshotPoint, Double, Microsoft.VisualStudio.Text.Editor.ViewRelativePosition, Double, Double, Boolean, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.ITextSnapshot)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.AdvanceSnapshot(Microsoft.VisualStudio.Text.TextSnapshotChangedEventArgs)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.AdvanceSnapshotOnUIThread(Microsoft.VisualStudio.Text.TextSnapshotChangedEventArgs)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.OnVisualBufferChanged(System.Object, Microsoft.VisualStudio.Text.TextContentChangedEventArgs)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.EventHandler`1<System.__Canon>, System.__Canon)
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.RawRaiseEvent(Microsoft.VisualStudio.Text.TextContentChangedEventArgs, Boolean)
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer+TextContentChangedEventRaiser.RaiseEvent(Microsoft.VisualStudio.Text.Implementation.BaseBuffer, Boolean)
   at Microsoft.VisualStudio.Text.Implementation.BufferGroup.RaiseEvents()
   at Microsoft.VisualStudio.Text.Implementation.BufferGroup.FinishEdit()
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer+TextBufferEdit.Apply()
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow+UIThreadOnly.InsertOutput(System.Collections.Generic.IEnumerable`1<System.String>, Int32)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow+UIThreadOnly.AppendOutput(System.Collections.Generic.IEnumerable`1<System.String>)
   at Microsoft.VisualStudio.InteractiveWindow.OutputBuffer.Flush()
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow+<>c.<Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow.FlushOutput>b__38_0(UIThreadOnly)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThread(System.Action`1<UIThreadOnly>)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow.FlushOutput()
   at Microsoft.CodeAnalysis.Editor.Interactive.InteractiveEvaluator.Microsoft.VisualStudio.InteractiveWindow.IInteractiveEvaluator.ResetAsync(Boolean)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow+UIThreadOnly+<ResetAsync>d__57.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.VisualStudio.InteractiveWindow.ExecutionResult, Microsoft.VisualStudio.InteractiveWindow, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow+UIThreadOnly+<ResetAsync>d__57, Microsoft.VisualStudio.InteractiveWindow, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ResetAsync>d__57 ByRef)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow+UIThreadOnly.ResetAsync(Boolean)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow+<>c__DisplayClass40_0.<Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindowOperations.ResetAsync>b__0(UIThreadOnly)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThread[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`2<UIThreadOnly,System.__Canon>)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindowOperations.ResetAsync(Boolean)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowCommandFilter.PreLanguageCommandFilterExec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowCommandFilter+CommandFilter.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindow.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
```

**Comment by minestarks** [comment]
@sharwell this is not a crash in the production environment. It's a nonfatal Watson. Is the `FailFast` limited to the test environment?

**Comment by sharwell** [comment]
> TestExtensionErrorHandler.HandleError

Looks like yes

**Comment by minestarks** [comment]
https://github.com/Microsoft/PTVS/pull/286/files has a different fix for the identical issue. Still trying to determine what this code is trying to do
