### ISSUE TITLE
Mocha require seems to be ignored for test discovery

### ISSUE THREAD

**Issue by lemvigh** [microsoft/nodejstools#2235]
I have a Mocha setup that uses module-alias and esm to load modules using ES6 import. That works fine when running that through npm using:
mocha --require module-alias/register --require esm "test/**/*.js"

I've added a mocha.json with the same require:
"require": [ "module-alias/register", "esm" ]

From the test log I can see that this configuration is read correctly, but the test discovery fails with an error message indicating that the ES6 import is not understood:

Test discovery error: mytest.js:1
(function (exports, require, module, __filename, __dirname) { import { assert } from 'chai'; 
                                                                     ^
SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    [...]

This is the exact same error I get when running through npm without --require esm.

**Comment by MrDoctorJ** [comment]
Having the same issue. Hoping to see this get fixed
