### ISSUE TITLE
DotNetTestDiscoverer throws System.MissingMethodException

### ISSUE THREAD

**Issue by sorinui** [microsoft/nodejstools#2410]
##### Expected Behavior 
Jasmine test to be visible in Test Explorer
##### Actual Behavior 
DotNetTestDiscoverer throws ``Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'`` and js tests are ignored

NTVS Version: 1.5.40629.1 Commit Hash:3f5cc0329815af3ffb948f08857446d206a9af36
Visual Studio Version: 2022 (17.3.5)
Node.js Version: 16.15.1

##### Steps to Reproduce
1. Create a unit test using the steps described in https://learn.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2022&tabs=jest#write-unit-tests-in-a-nodejs-project-njsproj
2. Click "Run Tests" in solution explorer

```TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.766, 11354364628531, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Resolving assembly.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.767, 11354364629819, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions'.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.767, 11354364630655, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions\System.Memory.dll', returning.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.767, 11354364631366, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Assembly path does not exist: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\Extensions\System.Memory.exe', returning.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.767, 11354364631701, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Searching in: 'C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\EBF\TESTEXPLORER'.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.767, 11354364632348, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Assembly path does not exist: 'C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\EBF\TESTEXPLORER\System.Memory.dll', returning.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.767, 11354364633069, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Assembly path does not exist: 'C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\EBF\TESTEXPLORER\System.Memory.exe', returning.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.767, 11354364633463, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Searching in: 'C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\C0CDJKHX.TP3'.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.768, 11354364639972, testhost.exe, AssemblyResolver.OnResolve: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51: Loading assembly 'C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\C0CDJKHX.TP3\System.Memory.dll'.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.770, 11354364665099, testhost.exe, AssemblyResolver.OnResolve: Resolved assembly: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, from path: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\C0CDJKHX.TP3\System.Memory.dll
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.830, 11354365265952, testhost.exe, TestDiscoveryManager.RunMessage: calling TestRunMessage(Error, Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.) callback.
TpTrace Error: 0 : 59616, 3, 2022/10/11, 23:29:51.831, 11354365269789, testhost.exe, Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.
TpTrace Verbose: 0 : 59616, 3, 2022/10/11, 23:29:51.831, 11354365270564, testhost.exe, TestRequestHandler.SendData: sending data from testhost: {"Version":7,"MessageType":"TestSession.Message","Payload":{"MessageLevel":2,"Message":"Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'."}}
TpTrace Verbose: 0 : 59616, 3, 2022/10/11, 23:29:51.831, 11354365271781, testhost.exe, MulticastDelegateUtilities.SafeInvoke: TestRunMessageLoggerProxy.SendMessage: Invoking callback 1/1 for Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscoveryManager., took 0 ms.
TpTrace Information: 0 : 59616, 3, 2022/10/11, 23:29:51.835, 11354365314537, testhost.exe, TestDiscoveryManager.RunMessage: calling TestRunMessage(Error, An exception occurred while test discoverer 'DotNetTestDiscoverer' was loading tests. Exception: Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.) callback.
TpTrace Error: 0 : 59616, 3, 2022/10/11, 23:29:51.835, 11354365315338, testhost.exe, An exception occurred while test discoverer 'DotNetTestDiscoverer' was loading tests. Exception: Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.
TpTrace Verbose: 0 : 59616, 3, 2022/10/11, 23:29:51.835, 11354365315858, testhost.exe, TestRequestHandler.SendData: sending data from testhost: {"Version":7,"MessageType":"TestSession.Message","Payload":{"MessageLevel":2,"Message":"An exception occurred while test discoverer 'DotNetTestDiscoverer' was loading tests. Exception: Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'."}}
TpTrace Verbose: 0 : 59616, 3, 2022/10/11, 23:29:51.835, 11354365316793, testhost.exe, MulticastDelegateUtilities.SafeInvoke: TestRunMessageLoggerProxy.SendMessage: Invoking callback 1/1 for Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscoveryManager., took 0 ms.
TpTrace Error: 0 : 59616, 3, 2022/10/11, 23:29:51.844, 11354365407309, testhost.exe, DiscovererEnumerator.DiscoverTestsFromSingleDiscoverer: System.MissingMethodException: Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.
   at Microsoft.Build.Shared.FileMatcher.IsFileNameMatch(String path, String pattern)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Build.Shared.FileMatcher.GetFilesForStep(RecursiveStepResult stepResult, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory)
   at Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(ConcurrentStack`1 listOfFiles, RecursionState recursionState, String projectDirectory, Boolean stripProjectDirectory, IList`1 searchesToExclude, Dictionary`2 searchesToExcludeInSubdirs, TaskOptions taskOptions)
   at Microsoft.Build.Shared.FileMatcher.GetFilesImplementation(String projectDirectoryUnescaped, String filespecUnescaped, List`1 excludeSpecsUnescaped)
   at Microsoft.Build.Shared.FileMatcher.<>c__DisplayClass67_0.<GetFiles>b__1(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Build.Shared.FileMatcher.GetFiles(String projectDirectoryUnescaped, String filespecUnescaped, List`1 excludeSpecsUnescaped)
   at Microsoft.Build.Internal.EngineFileUtilities.GetFileList(String directoryEscaped, String filespecEscaped, Boolean returnEscaped, Boolean forceEvaluateWildCards, IEnumerable`1 excludeSpecsEscaped, FileMatcher fileMatcher, Object loggingMechanism, IElementLocation includeLocation, IElementLocation excludeLocation, IElementLocation importLocation, BuildEventContext buildEventContext, String buildEventFileInfoFullPath, Boolean disableExcludeDriveEnumerationWarning)
   at Microsoft.Build.Internal.EngineFileUtilities.GetFileListEscaped(String directoryEscaped, String filespecEscaped, IEnumerable`1 excludeSpecsEscaped, Boolean forceEvaluate, FileMatcher fileMatcher, Object loggingMechanism, IElementLocation includeLocation, IElementLocation excludeLocation, IElementLocation importLocation, BuildEventContext buildEventContext, String buildEventFileInfoFullPath, Boolean disableExcludeDriveEnumerationWarning)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.NodejsTools.TestAdapter.ProjectTestDiscoverer.DiscoverTestsCore(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscovererEnumerator.DiscoverTestsFromSingleDiscoverer(LazyExtension`2 discoverer, Dictionary`2 discovererToSourcesMap, DiscoveryContext context, TestCaseDiscoverySink discoverySink, IMessageLogger logger, Double& totalAdaptersUsed, Double& totalTimeTakenByAdapters) 
```

**Comment by joj** [comment]
Hi! Do you have the Visual C++ workload installed? There was an incompatibility in that version that was fixed for 17.4. Thanks! J

**Comment by sorinui** [comment]
Yes I have the C++ workload installed. There seems to be an incompatibility specifically with the Google Test Adapter.
Is it possible to install the latest nodejstools without updating visual studio?

**Comment by joj** [comment]
Sorry, I was out last week. The issue is on the Google Test Adapter (also Boost), not in nodejs, so installing will not work. The issue is fixed now and updating will fix it for you, if you can. If you can't another option is to remove those two adapters in the setup (you can find them as part of the C++ workload).

**Comment by ThysBrits** [comment]
I have the same issue on VS 17.11.5, when my IDE is trying to discover tests of my Angular project.
```
[17/10/2024 12:08:31.927 pm] [Error] Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.
[17/10/2024 12:08:31.932 pm] [Error] An exception occurred while test discoverer 'JavascriptProjectTestDiscoverer' was loading tests. Exception: Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.
``` 
Also, when I switch between Solution and Folder view in my Solution Explorer, I get an error "Path was invalid, Parameter name: Path". If I try switching again, it works.
