### ISSUE TITLE
Exception when switching from Full IntelliSense to Quick IntelliSense

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#254]
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileInfo.get_Length()
   at Microsoft.NodejsTools.Project.NodejsProjectNode.IncludeNodejsFile(Microsoft.NodejsTools.Project.NodejsFileNode)
   at Microsoft.NodejsTools.Project.NodejsFileNode.get_ShouldAnalyze()
   at Microsoft.NodejsTools.Project.NodejsProjectNode.Reanalyze(Microsoft.VisualStudioTools.Project.HierarchyNode, Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer)
   at Microsoft.NodejsTools.Project.NodejsProjectNode.Reanalyze(Microsoft.VisualStudioTools.Project.HierarchyNode, Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer)
   at Microsoft.NodejsTools.Project.NodejsProjectNode.Reanalyze(Microsoft.VisualStudioTools.Project.HierarchyNode, Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer)
   at Microsoft.NodejsTools.Project.NodejsProjectNode.Reanalyze(Microsoft.VisualStudioTools.Project.HierarchyNode, Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer)
   at Microsoft.NodejsTools.Project.NodejsProjectNode.IntellisenseOptionsPageAnalysisLevelChanged(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at Microsoft.NodejsTools.Options.NodejsIntellisenseOptionsPage.set_AnalysisLevel(Microsoft.NodejsTools.Options.AnalysisLevel)
   at Microsoft.NodejsTools.Options.NodejsIntellisenseOptionsControl.SyncPageWithControlSettings(Microsoft.NodejsTools.Options.NodejsIntellisenseOptionsPage)
   at Microsoft.NodejsTools.Options.NodejsIntellisenseOptionsPage.SaveSettingsToStorage()
   at Microsoft.VisualStudio.Shell.DialogPage.OnApply(PageApplyEventArgs)
   at Microsoft.VisualStudio.Shell.DialogPage+DialogSubclass.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by kant2002** [comment]
If I manage to provide fix, does it goes to the current release? It is very likely would be trivial fix.

**Comment by mousetraps** [comment]
Yep, we're aiming to get everything tagged with "next-release" in for the July 20 release.
