### ISSUE TITLE
Error when loading project

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#277]
I run debug bits and have folowing error during project load:

```
Failed to find function record
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateFunctionExpression(ExpressionEvaluator ee, Node node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression[] astNodeList)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.NodejsTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node)
   at Microsoft.NodejsTools.Analysis.Analyzer.DDG.Walk(ReturnNode node)
   at Microsoft.NodejsTools.Parsing.ReturnNode.Walk(AstVisitor visitor)
   at Microsoft.NodejsTools.Analysis.Analyzer.DDG.Walk(Block node)
   at Microsoft.NodejsTools.Parsing.Block.Walk(AstVisitor walker)
   at Microsoft.NodejsTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.NodejsTools.Analysis.AnalysisUnit.Analyze(DDG ddg, CancellationToken cancel)
   at Microsoft.NodejsTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel)
   at Microsoft.NodejsTools.Analysis.JsAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.AnalysisQueue.Worker(Object threadStarted)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

will try to trace down which line of code produce that.

**Comment by kant2002** [comment]
Also the same error like #276 occurs during loading often too.

**Comment by billti** [comment]
This is a Debug assert, so won't impact release bits. Moving this out due to workload unless we see it impact releases.

**Comment by kant2002** [comment]
I willing to debug and fix that on my own. I really don't know where to start looking and from which parts NTVS consists. If somebody from the team could give guidance I could work independently.

**Comment by billti** [comment]
The assert is thrown from https://github.com/Microsoft/nodejstools/blob/35817ffdaa1797f95628a22f588fc3ed885f884b/Nodejs/Product/Analysis/Analysis/Analyzer/ExpressionEvaluator.cs#L521 , so if you set a conditional breakpoint there you should be able to break right before this occurs.

**Comment by kant2002** [comment]
Little bit more information.

Inside following JS file
```
router.get('/locations', function (req, res) {
        var devices = new Model();
        var subMenuId = req.query.id;
        devices.procedure({
            name: 'getMenuLocations',
            params: [
                {
                    name: 'subMenuId',
                    type: devices.utils.getType('int'),
                    value: subMenuId
                }
            ],
            success: function (result) {
                res.json(result[0]);
            },
            fail: function (err) {
                console.error("Failed to get menu locations from database.");
                res.json(err);
            }
        });
    });
```

When such assert is thrown, it is thrown for anonymous function. When investigate why is that I found that record identical to the `node` record is present in the `ee.Scope.GlobalEnvironment`, but it is not found, since it is different obejct, but it is looks like identical to the `node` variable value.

Don't yet know what this is means.

**Comment by mjbvz** [comment]
Try upgrading to [NTVS 1.2 Beta](https://github.com/Microsoft/nodejstools/releases) to use our new, modern ES6 IntelliSense engine. It should be much more stable and performant. 

And please report any issues you run into using the beta. ES6 IntelliSense is a big step forward, but we are always trying to make things better.
