### ISSUE TITLE
System.InvalidOperationException while closing project

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#392]
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Collections.Concurrent.BlockingCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TryAddWithNoTimeValidation(System.__Canon, Int32, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.TaskProvider.SendMessage(Microsoft.NodejsTools.Intellisense.WorkerMessage)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.ParseFile(Microsoft.NodejsTools.Analysis.IProjectEntry, System.String, System.IO.TextReader, Microsoft.NodejsTools.Analysis.IAnalysisCookie)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+<>c__DisplayClass4_0.<EnqueueFile>b__0()
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+<>c__DisplayClass5_0.<EnqueWorker>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

No repro on this. Occurred while exiting VS while a project was open (no files to save)

**Comment by rkavalap** [comment]
![vsnodejsclose](https://cloud.githubusercontent.com/assets/80310/10081726/3bc00424-62ab-11e5-8875-99f44684324d.PNG)

Unhandled exception in Microsoft.NodejsTools.Intellisense.TaskProvider.SendMessage (F:\72\src\Nodejs\Product\Nodejs\Intellisense\TaskProvider.cs:553) System.ObjectDisposedException: The collection has been disposed. Object name: 'BlockingCollection'. at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed() at System.Collections.Concurrent.BlockingCollection`1.get_IsCompleted() at Microsoft.NodejsTools.Intellisense.TaskProvider.Worker() at Microsoft.NodejsTools.Intellisense.TaskProvider.<SendMessage>b__24_0() at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudioTools.VsTaskExtensions.<HandleAllExceptions>d__4.MoveNext()
