### ISSUE TITLE
NPM refresh and JSON parse errors

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/nodejstools#405]
Just installed VS2015 (community) and Node 1.1

Created an Express 4 basic project.

Went to refresh (update) the NPM registry list and I get:

````
Registry url: http://registry.npmjs.org/
Current Time: 9/1/2015 4:44:22 PM
Last Refreshed: 5/20/2015 10:07:04 AM
Number of Results: 159002
Registry url: http://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\ysg4206\AppData\Local\Microsoft\Node.js Tools\NpmCache\3427da90-0f89-4fef-abcf-ba957317a972\since_packages.json
Downloading list of packages from http://registry.npmjs.org/-/all/since?stale=update_after&startkey=1432057204253
Download complete - updating database
Reading 1417 bytes from C:\Users\ysg4206\AppData\Local\Microsoft\Node.js Tools\NpmCache\3427da90-0f89-4fef-abcf-ba957317a972\since_packages.json (9/1/2015 4:44:26 PM)
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass7_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass22_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__22.MoveNext()
Download or parsing failed - deleting C:\Users\ysg4206\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting 3427da90-0f89-4fef-abcf-ba957317a972
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass7_0.<ParseResultsAndAddToDatabase>b__0()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass22_2.<ExecuteAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__13.MoveNext()
```

**Comment by DrYSG** [comment]
I may have solved the parse error. But even after it finished the complete download. It said it was updating the database. I let it run for 6 hours. Still updating. (Originally it claimed it the DB was 3 months old (I just downloded a fresh Nodejstools the day before).

```
Registry url: http://registry.npmjs.org/
Current Time: 9/2/2015 9:28:30 AM
Last Refreshed: 5/20/2015 10:07:04 AM
Number of Results: 159002
Registry url: http://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\ysg4206\AppData\Local\Microsoft\Node.js Tools\NpmCache\3427da90-0f89-4fef-abcf-ba957317a972\since_packages.json
Downloading list of packages from http://registry.npmjs.org/-/all/since?stale=update_after&startkey=1432057204253
Downloaded 1MB of the package list (48MB total)
Downloaded 2MB of the package list (48MB total)
Downloaded 3MB of the package list (48MB total)
Downloaded 4MB of the package list (48MB total)
Downloaded 5MB of the package list (48MB total)
Downloaded 6MB of the package list (48MB total)
Downloaded 7MB of the package list (48MB total)
Downloaded 8MB of the package list (48MB total)
Downloaded 9MB of the package list (48MB total)
Downloaded 10MB of the package list (48MB total)
Downloaded 11MB of the package list (48MB total)
Downloaded 12MB of the package list (48MB total)
Downloaded 13MB of the package list (48MB total)
Downloaded 14MB of the package list (48MB total)
Downloaded 15MB of the package list (48MB total)
Downloaded 16MB of the package list (48MB total)
Downloaded 17MB of the package list (48MB total)
Downloaded 18MB of the package list (48MB total)
Downloaded 19MB of the package list (48MB total)
Downloaded 20MB of the package list (48MB total)
Downloaded 21MB of the package list (48MB total)
Downloaded 22MB of the package list (48MB total)
Downloaded 23MB of the package list (48MB total)
Downloaded 24MB of the package list (48MB total)
Downloaded 25MB of the package list (48MB total)
Downloaded 26MB of the package list (48MB total)
Downloaded 27MB of the package list (48MB total)
Downloaded 28MB of the package list (48MB total)
Downloaded 29MB of the package list (48MB total)
Downloaded 30MB of the package list (48MB total)
Downloaded 31MB of the package list (48MB total)
Downloaded 32MB of the package list (48MB total)
Downloaded 33MB of the package list (48MB total)
Downloaded 34MB of the package list (48MB total)
Downloaded 35MB of the package list (48MB total)
Downloaded 36MB of the package list (48MB total)
Downloaded 37MB of the package list (48MB total)
Downloaded 38MB of the package list (48MB total)
Downloaded 39MB of the package list (48MB total)
Downloaded 40MB of the package list (48MB total)
Downloaded 41MB of the package list (48MB total)
Downloaded 42MB of the package list (48MB total)
Downloaded 43MB of the package list (48MB total)
Downloaded 44MB of the package list (48MB total)
Downloaded 45MB of the package list (48MB total)
Downloaded 46MB of the package list (48MB total)
Downloaded 47MB of the package list (48MB total)
Download complete - updating database
Reading 49639778 bytes from C:\Users\ysg4206\AppData\Local\Microsoft\Node.js Tools\NpmCache\3427da90-0f89-4fef-abcf-ba957317a972\since_packages.json (9/2/2015 9:29:06 AM)
```

**Comment by billti** [comment]
How did you solve the parse error? NTVS shouldn't have crashed if the catalog downloaded successfully from NPM.

Re the update not finished. I'm currently working on the fix for this ( see https://github.com/Microsoft/nodejstools/issues/415#issuecomment-137918268 ). The schema coming back from NPM has been changed and the code needs updating. Unfortunately it results in an infinite loop currently.

**Comment by DrYSG** [comment]
@billti , I read the #415 and it appears that I do have the same issue. Do you have a manual way to clear the NPM catalog (I.e. would I issue an npm cache clean?, https://docs.npmjs.com/cli/cache and since I did not install npm separately, where would I find this (you used to have a manual console back in the beta days, it was useful for things like this).

To answer your first question, *blush*, I did not want to embarrass our I.T. staff, they added a new twist to the firewall.. It now needs a user-agent in the header of all outbound calls (CONNECT, GET, POST, etc). So what I have to do, is run Fiddler as a local proxy, and have it add in the user-agent field. (the same problem exists in VS2015, when it tries to find extensions). So it is not a problem limited to node-tools, but I had no luck convincing the VS folks to start doing this.

**Comment by billti** [comment]
Thanks for the update. Looks like between the known issue (in review), the firewall issue, and the workaround of deleting the existing cached data, that you are up and running. Is this right?

I'll close this issue, but if not just comment with the latest and I'll reopen. Thanks!

**Comment by DrYSG** [comment]
Yea, I will still need the db merge, but for now, I can work.
