### ISSUE TITLE
VS2015 crashes when closing project

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#469]
When I close the NTVS project, VS crashes. I wait when WER collect information. Hopefully it would be available to you.

In case if this is related, I open project in VS, then close it, and reopen again, then I next time close project, VS crashes.

**Environment**
VS2015
NTVS 9-17-2015 Dev Build

Node 0.12
NPM 3.3.4

**Event Viewer**
```
Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x181b89f6
Faulting process id: 0xbe0
Faulting application start time: 0x01d0f2ea2039beb3
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: unknown
Report Id: cbdcf588-45bd-4825-b741-0f437d5d9e41
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by mousetraps** [comment]
Is that all the information available in the event viewer?

**Comment by kant2002** [comment]
Initially I start from reporting page, so I miss `.NET Runtime` event source

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at Microsoft.NodejsTools.Project.NodejsProjectNode.OnIdleNodeModules(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

```

**Comment by kant2002** [comment]
Also I look earleir in the Event log, and exactly the same exception happens to me earlier at least 2 times.

Also looks like timer which monitor changes in the node_modules does not disposed properly. https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Project/NodejsProjectNode.cs#L959

**Comment by jamesxv7** [comment]
I have the same issue but at opening a solution: 
```
Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x29f189dc
Faulting process id: 0x16ac
Faulting application start time: 0x01d0f475c99ee50a
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: unknown
Report Id: e4f44128-6069-11e5-9d9a-8243f1a82c6b
```
And the .NET Runtime

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at Microsoft.NodejsTools.Analysis.AnalysisUnit.AnalyzeWorker(Microsoft.NodejsTools.Analysis.Analyzer.DDG, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Analysis.Analyzer.DDG.Analyze(Microsoft.NodejsTools.Analysis.Deque`1<Microsoft.NodejsTools.Analysis.AnalysisUnit>, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Analysis.JsAnalyzer.AnalyzeQueuedEntries(System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+AnalysisQueue+GroupAnalysis.Analyze(System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+AnalysisQueue.Worker(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

Visual Studio start doing a restarting process and then VS2015 closes and open again. This happen at least once every day.

**Comment by mousetraps** [comment]
@jamesxv7 have you tried the latest dev build? I couldn't reproduce the issue, but it theoretically includes a fix - http://github.com/microsoft/nodejstools/releases

@kant2002 good find and thx for the additional stack trace. Indeed we should be properly disposing of the timer. Additionally we should verify that the fileNode is not null when we dequeue.

**Comment by jamesxv7** [comment]
Nope, I'll patch and let you know. Thanks for the hint!

**Comment by kant2002** [comment]
@mousetraps I have plenty of crashes for you :smile: not sure that all related to NTVS, that's why no reporting )))

**Comment by mousetraps** [comment]
@kant2002 well if they have NodejsTools in the namespace, it's a pretty good bet :wink:. Otherwise may as well report if you think it could possibly be related (we may not be able to do anything immediately, but if two ppl run into the same seemingly unrelated issue, then maybe it is indeed related).
