### ISSUE TITLE
Debugger retry logic continues attempting to connect even though the user has already forcefully closed the process

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#548]
This results it the UI freezing up until the debugger finishes attempting to reconnect
```
[23:04:31.8854893] --------------------------------------------------------------------------------
[23:04:32.8664892] AD7Engine Created (58467075)
[23:04:32.8874907] AD7Engine Called SetRegistryRoot
[23:04:32.8914900] AD7Engine Called SetLocale
[23:04:32.9044914] AD7Engine LaunchSuspended Called with flags 'LAUNCH_ENABLE_ENC' (58467075)
[23:04:34.5911157] Debugger connecting to URI: tcp://localhost:5858/
[23:04:36.6997887] Connection attempt 1 failed with: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:5858
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at Microsoft.NodejsTools.Debugger.Communication.TcpNetworkClient..ctor(String hostName, Int32 portNumber) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\TcpNetworkClient.cs:line 25
   at Microsoft.NodejsTools.Debugger.Communication.NetworkClientFactory.CreateNetworkClient(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\NetworkClientFactory.cs:line 32
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerConnection.Connect(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\DebuggerConnection.cs:line 129
[23:04:39.0816308] Connection attempt 2 failed with: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:5858
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at Microsoft.NodejsTools.Debugger.Communication.TcpNetworkClient..ctor(String hostName, Int32 portNumber) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\TcpNetworkClient.cs:line 25
   at Microsoft.NodejsTools.Debugger.Communication.NetworkClientFactory.CreateNetworkClient(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\NetworkClientFactory.cs:line 32
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerConnection.Connect(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\DebuggerConnection.cs:line 129
[23:04:41.5583271] Connection attempt 3 failed with: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:5858
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at Microsoft.NodejsTools.Debugger.Communication.TcpNetworkClient..ctor(String hostName, Int32 portNumber) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\TcpNetworkClient.cs:line 25
   at Microsoft.NodejsTools.Debugger.Communication.NetworkClientFactory.CreateNetworkClient(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\NetworkClientFactory.cs:line 32
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerConnection.Connect(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\DebuggerConnection.cs:line 129
[23:04:44.4605944] Connection attempt 4 failed with: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:5858
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at Microsoft.NodejsTools.Debugger.Communication.TcpNetworkClient..ctor(String hostName, Int32 portNumber) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\TcpNetworkClient.cs:line 25
   at Microsoft.NodejsTools.Debugger.Communication.NetworkClientFactory.CreateNetworkClient(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\NetworkClientFactory.cs:line 32
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerConnection.Connect(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\DebuggerConnection.cs:line 129
[23:04:46.7390253] Connection attempt 5 failed with: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:5858
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at Microsoft.NodejsTools.Debugger.Communication.TcpNetworkClient..ctor(String hostName, Int32 portNumber) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\TcpNetworkClient.cs:line 25
   at Microsoft.NodejsTools.Debugger.Communication.NetworkClientFactory.CreateNetworkClient(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\NetworkClientFactory.cs:line 32
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerConnection.Connect(Uri uri) in C:\repos\nodejstools2\Nodejs\Product\Nodejs\Debugger\Communication\DebuggerConnection.cs:line 129
```

**Comment by mousetraps** [comment]
This fix is now available in our [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by kant2002** [comment]
So this is should be re-opened again @mousetraps?

**Comment by mousetraps** [comment]
No, afaik it's fixed (unless you're seeing something different?). Looks like GH displays commits to every branch, though, even if they are not merged.

**Comment by kant2002** [comment]
Now I notice that this is on separate branch. Was thinking that you revert to fix some other issues with debugger.
