### ISSUE TITLE
Gruntfile.js failed to load: System.NotImplementedException at ..DependentFileNode.GetEditLabel()

### ISSUE THREAD

**Issue by solomon87** [Microsoft/nodejstools#552]
Installed 1.1 RC in Visual Studio 2015. My gruntfile started as a coffeescript file that I compiled which it then got picked up by the Task Runner and attempted to load. Here is the exception output:
```
10/19/2015 8:38:04 AM: System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudioTools.Project.DependentFileNode.GetEditLabel()
   at Microsoft.VisualStudioTools.Project.HierarchyNode.GetRelationalName()
   at Microsoft.VisualStudioTools.Project.ProjectNode.AddNewFileNodeToHierarchy(HierarchyNode parentNode, String fileName)
   at Microsoft.NodejsTools.Project.NodejsProjectNode.AddNewFileNodeToHierarchy(HierarchyNode parentNode, String fileName)
   at Microsoft.VisualStudioTools.Project.ProjectNode.AddItemWithSpecificInternal(UInt32 itemIdLoc, VSADDITEMOPERATION op, String itemName, UInt32 filesToOpen, String[] files, IntPtr dlgOwner, UInt32 editorFlags, Guid& editorType, String physicalView, Guid& logicalView, VSADDRESULT[] result, Nullable`1 promptOverwrite)
   at Microsoft.VisualStudioTools.Project.ProjectNode.AddItemWithSpecific(UInt32 itemIdLoc, VSADDITEMOPERATION op, String itemName, UInt32 filesToOpen, String[] files, IntPtr dlgOwner, UInt32 editorFlags, Guid& editorType, String physicalView, Guid& logicalView, VSADDRESULT[] result)
   at Microsoft.VisualStudioTools.Project.ProjectNode.AddItem(UInt32 itemIdLoc, VSADDITEMOPERATION op, String itemName, UInt32 filesToOpen, String[] files, IntPtr dlgOwner, VSADDRESULT[] result)
   at Microsoft.VisualStudioTools.Project.Automation.OAProjectItems.<>c__DisplayClass7_0.<AddItem>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by mousetraps** [comment]
Ahh, this is looks like that's due to our changes here:
https://github.com/Microsoft/nodejstools/commit/184f3259dcd2a6b6836507d674b9ca63fc435bcd#diff-eda080a72ca39cac394c109d986467bf

In particular, we rely on GetEditLabel() to produce the display name, but I didn't realize that's the only signal telling the project system that a file cannot be renamed and can sometimes be null or throw a NotImplementedException.
https://github.com/Microsoft/nodejstools/blob/8169f1e6fe7c83e3f4061631a44de79b3e80ec73/Common/Product/SharedProject/DependentFileNode.cs#L57-L64

One idea is simply adding a new GetFileOrDirectoryName() method that calls CommonUtils.GetFileOrDirectoryName(Url) under the covers, and referring to that in spots where we want to get the name, but are not actually interested in editing the name.

**Comment by mousetraps** [comment]
@solomon87 while we have an idea of where this is coming from... I can't reproduce this issue, so would be unable to verify the fix... have you tried with the latest versions of NTVS (https://github.com/microsoft/nodejstools/issues/releases), web essentials, and other potentially extensions (file nesting)? Do you have a simple project that reproduces the issue?
