### ISSUE TITLE
Visual studio crashes every time I save my package.json

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#621]
I've disabled all the extensions I can but every time I save the package.json VS crashes with the following (according to when I try to debug the crash in VS which it sometimes lets me do)

<pre>
An unhandled exception of type 'System.NullReferenceException' occurred in mscorlib.dll

Additional information: Object reference not set to an instance of an object.#
</pre>

Here's my package.json

<pre>
{
  "private": true,
  "name": "brian",
  "description": "Easy access to media and communications",
  "homepage": "https://github.com/OpenDirective/brian",
  "bugs": {
    "url": "https://github.com/OpenDirective/brian/issues"
  },
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": "git://github.com/OpenDirective/brian"
  },
  "keywords": [
    "Access",
    "Assistive Technology",
    "Cognitive"
  ],
  "engines": {
    "node": ">=4.2.0"
  },
  "dependencies": {
    "hapi": "11.1.2",
    "inert": "3.2.0"
  },
  "devDependencies": {
    "eslint": "^1.10.1",
    "eslint-config-hapi": "^7.0.0",
    "eslint-plugin-hapi": "^4.0.0"
  },
  "scripts": {
    "start": "node server.js",
    "test": "eslint .\\"
  },
  "author": "Steve Lee (http://opendirective.com)",
  "license": "Apache-2.0"
}

</pre>

I'm using VS community 2015 update 1
If you need more to repo the problem I can for the repository

**Comment by SteveALee** [comment]
@mousetraps 
* I tried creating a new project from the cmd line template and copying source files and save package.json does not crash

* I copied the entire project to C:\projects\xxx and deleted as many non source files and folders as I could. Still crashes

**Comment by SteveALee** [comment]
OK so it still crashes with everything except .nsjproj, .sln and package.json removed. So it must be the VS config files so I've attached them in case anyone can see anything obvious



[brian.njsproj.txt](https://github.com/Microsoft/nodejstools/files/49124/brian.njsproj.txt)
[brian.sln.txt](https://github.com/Microsoft/nodejstools/files/49123/brian.sln.txt)

**Comment by SteveALee** [comment]
OK so the problem is somehow the package.json is displayed in the solution explorer but NOT included in it. The checkedin status is icon is next to it.

I used "include in project" and all is well.

So how could I have got into this state? The Update 1 upgrade? Whatever it should not crash VS

I guess this is probably a VS issue, not nodejstools?

@mousetraps can you pass this on to anyone who might be interested? Andthen close it.

Oh one thing the file before in the solution has a .txt extension so I tried to rename without the extension in solution explorer. It got very confused? Perhaps that caused a corruption?

**Comment by mousetraps** [comment]
@SteveALee  thanks for the additional info! Managed to get a repro:

1. create blank node.js console app project
2. exclude package.json from the project
3. open package.json, start typing something (e.g. add azure to the dependencies), and save
4. VS crashes with the following stack:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory.TryGetNpmCommandServiceFromProject(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.String, Microsoft.VisualStudio.Web.PackageManagement.Npm.INpmCommandService ByRef)
   at Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory+<>c__DisplayClass2_0+<<GetNpmCommandService>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.Threading.Tasks.Task`1<System.__Canon>>, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions)
   at Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory.GetNpmCommandService(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.String)
   at Microsoft.VisualStudio.JSON.Package.Npm.NpmPackageManagerInitializer.GetNpmCommandService(Microsoft.VisualStudio.Text.ITextBuffer)
   at Microsoft.VisualStudio.JSON.Package.Npm.NpmPackageManagerInitializer+<<get_InstallPackagesAction>b__4_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

We'll pass it onto the web tools team, but keep it open right for now so we can remember to follow up. Thanks again!

**Comment by lclghst** [comment]
Thanks @SteveALee the include in project workaround fixed it for me. 

I had resorted to safe-mode with extensions disabled previously. :mask:

**Comment by uniquelau** [comment]
Quick +1 on this issue, [resolved by included as above](https://github.com/Microsoft/nodejstools/issues/621#issuecomment-161111787).

**Comment by chapeti** [comment]
+1

**Comment by paulvanbrenk** [comment]
I no longer reproduce this in VS 2017
