### ISSUE TITLE
VS keeps crashing while "Loading cached Node.js analysis for project"

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/nodejstools#623]
Visual Studio keeps crashing when it tries to load my project. In the UI, it is during or right after these messages:
"Loading cached Node.js analysis for project"
"Cached Node.js analysis loaded."

![image](https://cloud.githubusercontent.com/assets/80104/11609953/63062f78-9b49-11e5-9eca-dad87d7a413c.png)

![image](https://cloud.githubusercontent.com/assets/80104/11609954/72dda1a6-9b49-11e5-8e61-f610202f27c8.png)

Event Viewer has several of these types of errors in Windows Logs > Application. Each one was a crash of Visual Studio.

![image](https://cloud.githubusercontent.com/assets/80104/11609977/1502682c-9b4a-11e5-852e-182f6d8942b2.png)

![image](https://cloud.githubusercontent.com/assets/80104/11609966/d7c36592-9b49-11e5-93c6-0962d0355ac6.png)

**Comment by ctaggart** [comment]
Errors as text instead of images:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.NodejsTools.Analysis.ModuleTreeExtensions+<>c.<GetChildrenExcludingNodeModules>b__0_0(Microsoft.NodejsTools.Analysis.ModuleTree)
   at System.Linq.Enumerable+WhereArrayIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.NodejsTools.Analysis.Analyzer.RequireAnalysisUnit.AddChildVisibilitiesExcludingNodeModules(Microsoft.NodejsTools.Analysis.ModuleTree)
   at Microsoft.NodejsTools.Analysis.Analyzer.RequireAnalysisUnit.AddChildVisibilitiesExcludingNodeModules(Microsoft.NodejsTools.Analysis.ModuleTree)
   at Microsoft.NodejsTools.Analysis.Analyzer.RequireAnalysisUnit.AddChildVisibilitiesExcludingNodeModules(Microsoft.NodejsTools.Analysis.ModuleTree)
   at Microsoft.NodejsTools.Analysis.Analyzer.RequireAnalysisUnit.AddChildVisibilitiesExcludingNodeModules(Microsoft.NodejsTools.Analysis.ModuleTree)
   at Microsoft.NodejsTools.Analysis.Analyzer.RequireAnalysisUnit.AnalyzeWorker(Microsoft.NodejsTools.Analysis.Analyzer.DDG, System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Analysis.JsAnalyzer+TreeUpdateAnalysis.Analyze(System.Threading.CancellationToken)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+AnalysisQueue.Worker(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at Newtonsoft.Json.Linq.JToken.EnsureValue(Newtonsoft.Json.Linq.JToken)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(Newtonsoft.Json.Linq.JToken)
   at Microsoft.NodejsTools.Debugger.Commands.ChangeLiveCommand.ProcessResponse(Newtonsoft.Json.Linq.JObject)
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerClient+<SendRequestAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.NodeDebugger+<TrySendRequestAsync>d__98.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.NodeDebugger+<UpdateModuleSourceAsync>d__62.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.DebugEngine.AD7Engine+<>c__DisplayClass103_0+<<OnDocumentSaved>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerClient+<RunWithRequestExceptionsHandled>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by kant2002** [comment]
Second exception info seems to be this is related to #584, and if you are using 1.1 Final, that should be fixed by now. @ctaggart seems that you are using 1.1 RC, since my 1.1 Final version has 1.1.31117.00 version.

First one exception seems to be related to #595 which are already in the 1.1 Final as well.

Could you confirm that you are using Final verison of NTVS?

**Comment by ctaggart** [comment]
I thought I was on the 1.1 final. Sorry about that, but thanks for helping me! It seems to be working.

https://github.com/Microsoft/nodejstools/releases/tag/v1.1
