### ISSUE TITLE
OOM during running tests

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#639]
After some time running test suite following error happens

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StreamReader.ReadToEnd()
   at Microsoft.NodejsTools.Npm.ReaderPackageJsonSource..ctor(TextReader reader) in E:\d\kant\GitHub\nodejstools\Nodejs\Product\Npm\ReaderPackageJsonSource.cs:line 26
   at Microsoft.NodejsTools.Npm.FilePackageJsonSource..ctor(String fullPathToFile) in E:\d\kant\GitHub\nodejstools\Nodejs\Product\Npm\FilePackageJsonSource.cs:line 36
   at Microsoft.NodejsTools.Npm.DirectoryPackageJsonSource..ctor(String fullDirectoryPath) in E:\d\kant\GitHub\nodejstools\Nodejs\Product\Npm\DirectoryPackageJsonSource.cs:line 24
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages, Dictionary`2 allModules, Int32 depth) in E:\d\kant\GitHub\nodejstools\Nodejs\Product\Npm\SPI\RootPackage.cs:line 33
   at Microsoft.Nodej......
<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by mousetraps** [comment]
Interesting, thanks - do you have any reliable repro steps? And feel free to share the code w/ us privately - ntvshelp at microsoft dot com

**Comment by mousetraps** [comment]
Ahh, you meant while running tests... haven't run into this issue - could you figure out which test is specifically causing this issue for you? we can try to decrease the size of it. Also does it happen when you run the tests in release mode?

**Comment by mjbvz** [comment]
We've made a lot of fixes in the `package.json` logic to reduce memory usage since this issue was filed, and I have not been able to repo this recently. 

@kant2002 If you are still able to repo, please let us know and provide some steps so we can investigate. Thanks
