### ISSUE TITLE
NodejsPackage created multiple times

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#641]
During running tests

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
NodejsPackage created multiple times
   at Microsoft.NodejsTools.NodejsPackage..ctor() in E:\d\kant\GitHub\nodejstools\Nodejs\Product\Nodejs\NodejsPackage.cs:line 127
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at Microsoft.VisualStudio.Shell.Interop.IVsCreateAggregateProject.CreateAggregateProject(String pszProjectTypeGuids, String pszFilename, String pszLocation, String pszName, UInt32 grfCreateFlags, Guid& iidProject, IntPtr& ppvProject)
   at Microsoft.VisualStudioTools.Project.ProjectFactory.CreateProject(String fileName, String location, String name, UInt32 flags, Guid& projectGuid, IntPtr& project, Int32& canceled) in E:\d\kant\GitHub\nodejstools\Common\Product\SharedProject\ProjectFactory.cs:line 124
   at Microsoft.VisualStudioTools.Project.FlavoredProjectFactoryBase.Microsoft.VisualStudio.Shell.Interop.IVsProjectFactory.CreateProject(String fileName, String location, String name, UInt32 flags, Guid& projectGuid, IntPtr& project, Int32& canceled) in E:\d\kant\GitHub\nodejstools\Common\Product\SharedProject\FlavoredProjectFactoryBase.cs:line 60
```

**Comment by mousetraps** [comment]
Can you please grab the name of the test that caused this issue?

**Comment by mjbvz** [comment]
I haven't seen this issue recently.

@kant2002 If you are still able to repo, please let us know and provide some steps so we can investigate. Thanks
