### ISSUE TITLE
Winjs with nodejs

### ISSUE THREAD

**Issue by kanaaan** [Microsoft/nodejstools#661]
I have added WinJS to Blank Node.js web application using nmp.

Then I have added to following line in my server.js:
var WinJS = require('winjs');
But when I run the application I'm getting the following error:

Debugger listening on port 5858
 C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:4746
    var platform = _Global.navigator.platform;
                                    ^

TypeError: Cannot read property 'platform' of undefined
    at baseUtilsInit (C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:4746:37)
    at load (C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:110:28)
    at C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:97:32
    at Array.map (native)
    at resolve (C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:80:29)
    at load (C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:108:20)
    at C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:97:32
    at Array.map (native)
    at resolve (C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:80:29)
    at load (C:\src\SAGA\SAGA\node_modules\winjs\js\base.js:108:20)
 Press any key to continue...

Any help is welcome.
Thks,

**Comment by mousetraps** [comment]
This looks like an issue with your code or WinJS, not with NTVS. If it works when your run the app in the command line, I'll be happy to re-open and investigate the reason behind the disparate behavior, otherwise I suggest reading through WinJS docs or filing an issue on the WinJS repo.
