### ISSUE TITLE
Many CI ReplWindowTests failing with System.InvalidOperationException

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#672]
The issue does not occur locally.

```
Error message:
Test method NodejsTests.ReplWindowTests.TestConsoleLog threw exception: 

System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
Error stack trace:
    at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)

   at Microsoft.NodejsTools.Repl.NodejsReplEvaluator.ListenerThread.ProcessExitedWorker() in C:\projects\nodejstools\Nodejs\Product\Nodejs\Repl\NodejsReplEvaluator.cs:line 300

   at Microsoft.NodejsTools.Repl.NodejsReplEvaluator.ListenerThread.Dispose(Boolean disposing) in C:\projects\nodejstools\Nodejs\Product\Nodejs\Repl\NodejsReplEvaluator.cs:line 465

   at Microsoft.NodejsTools.Repl.NodejsReplEvaluator.Dispose() in C:\projects\nodejstools\Nodejs\Product\Nodejs\Repl\NodejsReplEvaluator.cs:line 161

   at NodejsTests.ReplWindowTests.TestConsoleLog() in C:\projects\nodejstools\Nodejs\Tests\Core\ReplWindowTests.cs:line 100
```

**Comment by mjbvz** [comment]
We've just disabled all the ReplWindow tests in AppVeyor for now by adding the `"AppVeyorIgnore"` test category: #731 

I took a quick look at fixing this and it may be as simple as changing `SetResult` to `TrySetResult`, but it's not clear to me why these are failing in AppVeyor only in the first place.
