### ISSUE TITLE
Many CI Debugger Tests failing with SocketException

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#673]
This issue does not occur locally.

```
Error message:
Test method NodejsTests.Debugger.DebuggerTests.Startup_NoBreakOnEntryPointTracePoint threw exception: 

System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it [::1]:5858
Error stack trace:
    at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)

   at Microsoft.NodejsTools.Debugger.Communication.NetworkClientFactory.CreateNetworkClient(Uri uri) in C:\projects\nodejstools\Nodejs\Product\Nodejs\Debugger\Communication\NetworkClientFactory.cs:line 32

   at Microsoft.NodejsTools.Debugger.Communication.DebuggerConnection.Connect(Uri uri) in C:\projects\nodejstools\Nodejs\Product\Nodejs\Debugger\Communication\DebuggerConnection.cs:line 151

   at Microsoft.NodejsTools.Debugger.NodeDebugger.StartListening() in C:\projects\nodejstools\Nodejs\Product\Nodejs\Debugger\NodeDebugger.cs:line 483

   at NodejsTests.Debugger.BaseDebuggerTests.DebugProcess(String filename, Action`1 onProcessCreated, Action`2 onLoadComplete, String interpreterOptions, NodeDebugOptions debugOptions, String cwd, String arguments, Boolean resumeOnProcessLoad) in C:\projects\nodejstools\Nodejs\Tests\Core\Debugger\BaseDebuggerTests.cs:line 108

   at NodejsTests.Debugger.BaseDebuggerTests.TestDebuggerSteps(String filename, IEnumerable`1 steps, String interpreterOptions, Action`1 onProcessCreated, Nullable`1 defaultExceptionTreatment, ICollection`1 exceptionTreatments, String scriptArguments) in C:\projects\nodejstools\Nodejs\Tests\Core\Debugger\BaseDebuggerTests.cs:line 431

   at NodejsTests.Debugger.DebuggerTests.Startup_NoBreakOnEntryPointTracePoint() in C:\projects\nodejstools\Nodejs\Tests\Core\Debugger\DebuggerTests.cs:line 474
```

**Comment by mousetraps** [comment]
Firewall issue. Resolved by adding the following to the AppVeyor install script:
```
$node = which node
$node = $node.Replace("/c/", "C:\").Replace("/", "\") + ".exe"
echo $node
netsh advfirewall firewall add rule name="Nodejs" dir=in action=allow program="$node" enable=yes
```

**Comment by mousetraps** [comment]
hrmm... oddly enough it works fine when running the test alone: https://ci.appveyor.com/project/mousetraps/nodejstools/build/1.0.82/job/4c09yom083nc588y/tests

But not when running the full suite: https://ci.appveyor.com/project/mousetraps/nodejstools/build/1.0.84/job/0qscgra7e21lab1m/tests

**Comment by mjbvz** [comment]
I looked into this a little more and it seems there are two types of problems with the DebuggerTests: the socket issue you describe and timeouts waiting for a ProcessExit signal. The latter repos locally, and may be related to #89.
