### ISSUE TITLE
VS crashed when debugger stopping

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#911]
1. I start NTVS under debugger 
2. Run NodeJS project inside NTVS under debugger.
3. Do some testing
4. Press 'Terminate debugger button'
5. Almost immediately close NodeJS console application
   6, Appear Debug prompt
6. NTVS instance closed and I was in regular VS instance

```
An unhandled exception is about to terminate the process:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NodejsTools.Debugger.DebugEngine.AD7Engine.<>c__DisplayClass103_0.<<OnDocumentSaved>b__0>d.MoveNext() in <somefolder>nodejstools\Nodejs\Product\Nodejs\Debugger\DebugEngine\AD7Engine.cs:line 1242
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerClient.<RunWithRequestExceptionsHandled>d__5.MoveNext() in <somefolder>nodejstools\Nodejs\Product\Nodejs\Debugger\Communication\DebuggerClient.cs:line 81
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by mjbvz** [comment]
I'm not been able to repo this exact crash, but did discover a fun new bug trying to do so: #912 

For this bug, is this the correct repo?

1. Create new blank Javascript Node console application using NTVS.
1. Launch debugger for it.
1. In VS, click the stop debugging button.
1. Then, very quickly before the console window disappears, hit the close button on it?

Does this crash every time you try?  When I hit the stop button, I see the console window closed almost instantly so I'm not able to close it.

**Comment by kant2002** [comment]
Unfortunately I also not able to reproduce it consistently, It happens to me after I spend a lot of time inside NTVS running under debugger. That's not very usual setup, but it helps me find small issues which I could report better.
I will keep on eye on this, and try to reproduce it consistently if this will be possible with your null check :smile:.

**Comment by kant2002** [comment]
Again hit this bug. I close Node process using Ctrl+C, likely that was the case and first time. Will try to repro again.

**Comment by paulvanbrenk** [comment]
Closing, as we're not investing in Node 6 support unless there's a critical bug.
